### Get all books
GET http://localhost:3000/api/books
###
### GET book by id
GET http://localhost:3000/api/books/1
###
### Create book
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "name": " as",
  "author": "jk",
  "gender": "terror",
  "is_available": true
}
###
### Updated book
PUT http://localhost:3000/api/books/1
Content-Type: application/json

{
  "code": 1,
  "name": "Eso",
  "author": "stephen king",
  "gender": "terror",
  "is_available": true
}
###

### Delete book
DELETE http://localhost:3000/api/books/1

### Get all users
GET http://localhost:3000/api/users
###

### Get user by id
GET http://localhost:3000/api/users/1
###

### Create user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "fullName": "lucio albanesi",
  "username": "lucioalba",
  "password": "123",
  "email": "lucioalba02@gm"
}
###

### Update user
PUT http://localhost:3000/api/users/1
Content-Type: application/json

{
  "id": 1,
  "fullName": "lucio albanesi",
  "username": "lucioalba",
  "password": "456",
  "email": "lucioalba02@gmai.com"
}
###

### Delete user
DELETE http://localhost:3000/api/users/1
