### Get all books
GET http://localhost:3000/api/books
###
### GET book by id
GET http://localhost:3000/api/books/4
###
### Create book
POST http://localhost:3000/api/books
Content-Type: application/json

{
  "id": 1,
  "title": "harry poter",
  "author": {
    "id": 2
  },
  "gender": {
    "id": 3
  }
}
###
### Updated book
PUT http://localhost:3000/api/books/1
Content-Type: application/json

{
  "name": "Eso",
  "author": {
    "id": 1
  },
  "gender": {
    "id": 1
  }
}
###

### Delete book
DELETE http://localhost:3000/api/books/1


### Get all authors
GET http://localhost:3000/api/authors
###
### Get author by id
GET http://localhost:3000/api/authors/2
###
### Create author
POST http://localhost:3000/api/authors
Content-Type: application/json

{
  "id": 0,
  "name": "jk rowling"
}
###
### Update author
PUT http://localhost:3000/api/authors/1
Content-Type: application/json

{
  "name": "Stephen King"
}
###
### Delete author
DELETE http://localhost:3000/api/authors/1

### Get all genders
GET http://localhost:3000/api/genders
###
### Get gender by id
GET http://localhost:3000/api/genders/1
###
### Create gender
POST http://localhost:3000/api/genders
Content-Type: application/json

{
  "id": 1,
  "description": "fantasia"
}
###
### Update gender
PUT http://localhost:3000/api/genders/1
Content-Type: application/json

{
  "description": "Horror"
}
###
### Delete gender
DELETE http://localhost:3000/api/genders/1
###
POST http://localhost:3000/api/book_copies
Content-Type: application/json

{
  "id": 0,
  "is_available": true,
  "condition": "GOOD",
  "book": {
    "id": 2
  }
}

### Get All Persons
GET http://localhost:3000/api/persons
### Get person by id
GET http://localhost:3000/api/persons/1

### Create Person
POST http://localhost:3000/api/persons
Content-Type: application/json

{
  "id": 1,
  "name":"fideo",
  "lastName": "di maria",
  "address": "direccion",
  "phone": "123455",
  "emailAddress": "dimaria@gmail.com"
}
### Update Person
PUT http://localhost:3000/api/persons/1
Content-Type: application/json

{
"id": 1,
"name":"fideo",
"lastName": "di maria",
"address": "direccion",
"phone": "123455",
"emailAddress": "dimaria@gmail.com"
}
###
DELETE http://localhost:3000/api/persons/4
### Get user by id
GET http://localhost:3000/api/users/1
### Create User
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "id": 0,
  "username": "c",
  "password": "Messi123",
  "person": {"id":  5}
}
###
DELETE http://localhost:3000/api/users/6

###
POST http://localhost:3000/api/loans
Content-Type: application/json

{
  "id": 0,
  "start_date": "2025-10-30T00:00:00.000Z",
  "end_date": "2025-11-15T00:00:00.000Z",
  "person": {
    "id": 6
  },
  "bookCopies": [

    { "id": 5 }
  ]
}
###
DELETE http://localhost:3000/api/loans/1